name: hello world

run-name: say hello world

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/actions.yaml

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 1
      - name: say hello
        run: echo hello
  say-world:
    runs-on: ubuntu-latest
    #needs: say-hello
    steps:
      - run: echo world
