name: artifact

run-name: Upload artifact

on: push

jobs:
  create-and-upload:
    runs-on: ubuntu-latest
    steps:
      - run: mkdir artifact
      - run: echo hello > artifact/hello.txt
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: artifact/hello.txt
