name: build-and-push

on:
  push:
    branches:
      - main
    paths:
      - 'app/**'
      - .github/workflows/build-and-push.yml

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: sha
        run: echo "short=$(git rev-parse --short $GITHUB_SHA)" >> "$GITHUB_OUTPUT"
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: app
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ steps.sha.outputs.short }}
