name: Deploy

on:
  push:
    branches:
      - main
    paths:
      - manifest/app.yaml

jobs:
  deploy-to-eks:
    uses: ./.github/workflows/deploy-to-eks.yaml
    with:
      assume_role: ${{ secrets.assume_role }}
      eks_region: ap-northeast-1
      eks_cluster_name: poc
      manifest: manifest/app.yaml

  #deploy-to-ecs:
    # https://docs.github.com/ja/actions/deployment/deploying-to-your-cloud-provider/deploying-to-amazon-elastic-container-service

  # deploy-to-gke:
  #   # https://docs.github.com/ja/actions/deployment/deploying-to-your-cloud-provider/deploying-to-google-kubernetes-engine

  # deploy-to-k8s:
