name: hello

run-name: say hello

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/hello.yaml

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: say hello
        run: echo "hello"
  goodbye:
    needs: hello
    # usesを使うと別のワークフローを呼び出すことができる
    # この場合、runs-onやstepsは不要となる
    uses: ./.github/workflows/goodbye.yaml
