name: hello

run-name: say hello

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/hello.yaml

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: hello
        run: echo "hello"
  say-goodbye:
    needs: say-hello
    uses: ./.github/workflows/goodbye.yaml
