name: hello

on:
  push:
    branches:
      - main
    paths:
      - 'app/**'
      - .github/workflows/say-hello.yaml

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: hello
        run: echo "hello"
  say-goodbye:
    needs: say-hello
    runs-on: ubuntu-latest
    steps:
      - name: goodbye
        run: echo "goodbye"
