name: hello

on:
  push:
    branches:
      - main
    paths:
      - 'app/**'
      - .github/workflows/say-hello.yaml

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: hello
        run: echo "hello world"
